/*
*date:2016-2-22
*/
$(document).ready(function(){
	$("button[name='btn_turnLogin']").click(function(){
		$("#index_acount_select").addClass("hidden");
		$("#index_acount_login").removeClass("hidden");
	});
	$("button[name='btn_turnRegister']").click(function(){
		$("#index_acount_select").addClass("hidden");
		$("#index_acount_register").removeClass("hidden");
	});
	$("button[name='btn_back']").click(function(){
		$("#index_acount_select").removeClass("hidden");
		$("#index_acount_login").addClass("hidden");
		$("#index_acount_register").addClass("hidden");
	});
	$("button[name='btn_login']").click(function(){
		$.ajax({
			type:"get",
			async:false,
			url:"http://192.168.1.102:8080/BridgeCount/Register/newplayer.do",
			data:{
				playername:"123",
				username:"321",
				password:"231"
			},
			dataType:"jsonp",
			jsonp:"callbackparam",
			jsonpCallback:"?",
			success:function(result){

			},
			error:function(){
				alert("失败");
			}
		});
	});
	$("button[name='btn_register']").click(function(){
		
	});
});